on:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        description: 'manylinux version, eg: 2025.11.25-1'
        type: string
        required: true
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_manylinux:
    name: ${{ matrix.policy }}_${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04
            policy: manylinux_2_38
            platform: loongarch64

          - arch: arm64
            runner: ubuntu-24.04-arm
            policy: manylinux_2_38
            platform: loongarch64

          - arch: amd64
            runner: ubuntu-24.04
            policy: musllinux_1_2
            platform: loongarch64

          - arch: arm64
            runner: ubuntu-24.04-arm
            policy: musllinux_1_2
            platform: loongarch64

    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepar build
        run: |
          if [ "${{ github.event_name }}" = "schedule" ] || [ "${{ github.event_name }}" = "push" ]; then
            IMAGE_TAG=latest
          else
            IMAGE_TAG=${{ inputs.version }}
          fi
          BASE_IMAGE="ghcr.io/${{ github.repository_owner }}/${{ matrix.policy }}_${{ matrix.platform }}:${IMAGE_TAG}"
          echo "BASE_IMAGE=${BASE_IMAGE}" >> $GITHUB_ENV

          echo "========== Build Args =========="
          echo "BASE_IMAGE=${BASE_IMAGE}"

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/loong64
          push: true
          build-args: |
            RUNNER_ARCH
            BASE_IMAGE
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.policy }}-clang:${{ matrix.platform }}-${{ matrix.arch }}
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
